export enum EnumApiError {
    MISSING_FIELDS = "MISSING_FIELDS",
    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS",
    FAILED_CREATE = "FAILED_CREATE",
    UNATHENTICATED = "UNATHENTICATED",
    INVALID_TOKEN = "INVALID_TOKEN",
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
}